### ISSUE TITLE
Container becomes unhealthy and restarts

### ISSUE THREAD

**Issue by jstawski** [Azure/app-service-quickstart-docker-images#214] opened 2019-01-02 20:11 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> I wish I knew... the website/container eventually becomes unresponsive and requests take too long, eventually timing out. Then it starts working again until it stops again.

### Any log messages given by the failure
> I found the following log message troubleshooting this: `ERROR - Container for sitename site sitename is unhealthy, Stopping site.` Further investigation, I found a bunch of `upstream timed out` errors on `/LogFiles/nginx/error.log`: `2019/01/02 12:11:04 [error] 157#157: *4946 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.1
9.0.1, server: _, request: "GET /privacy HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock", host: "my.site.com"`. I'm not sure if the above two are related or not

### Expected/desired behavior
> Container should be healthy and active

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LeonZhang77** [comment] 2019-01-03 02:42
which container you are using? 
maybe you can check below points:
1) is /var/run/php/php7.0-fpm.sock exist? 
2) if it's exist, run "chmod 777 /var/run/php/php7.0-fpm.sock", is this issue resolved? 
3) check /home/LogFiles/nignx, pay attention of file szie, make sure it's not too big, it slow-down performance if it's big.
4) is this issue resolved by restart web app?

**Comment by jstawski** [comment] 2019-01-03 15:59
which container you are using?
> appsvcorg/wordpress-alpine-php:0.7

is /var/run/php/php7.0-fpm.sock exist?
> yes

if it's exist, run "chmod 777 /var/run/php/php7.0-fpm.sock", is this issue resolved?
> It already is set to 777
srwxrwxrwx    1 root     root             0 Jan  3 02:31 php7.0-fpm.sock

check /home/LogFiles/nignx, pay attention of file szie, make sure it's not too big, it slow-down performance if it's big.
> It doesn't sound like it is too big, 16 MB.
![image](https://user-images.githubusercontent.com/873800/50647429-854c2c80-0f46-11e9-91e0-4652f05571b5.png)

is this issue resolved by restart web app?
> yes

**Comment by LeonZhang77** [comment] 2019-01-08 02:50
I just pushed appsvcorg/wordpress-alpine-php:0.71, it allow you select listen type of php-fpm/nginx, socket or port? 

# Choose Listen Type of php-fpm/nginx
1. By default, ```LISTEN_TYPE``` = socket.
2. Update App Setting ```LISTEN_TYPE``` = port if you perfer to listening from TCP/IP.


but i also met same issue when listening to 127.0.0.1:9000, i haven't figure out root cause.

**Comment by LeonZhang77** [comment] 2019-01-08 02:51
BTW, according to test, socket is faster than port.

**Comment by LeonZhang77** [comment] 2019-01-08 09:31
I guess this issue is related with supervisord, keep trying.

**Comment by LeonZhang77** [comment] 2019-01-18 03:09
@jstawski , could you please have a try of appsvcorg/wordpress-alpine-php:0.72.

i have run stress testing on it for a week, looks more robust.
it still throw "(110: Operation timed out)", but it hasn't caused to restart and kept providing service.

i am closing this issue.

**Closed by LeonZhang77** 2019-01-18 03:09 UTC
